### ISSUE TITLE
Build compatible for Apple M1 CPU

### ISSUE THREAD

**Issue by wongster80** [apache/cloudstack-cloudmonkey#113] opened 2022-03-22 19:19 UTC
Hi,
Is CMK built for Apple M1 CPU, because I've been getting this error running cmk.

 % sysctl -n machdep.cpu.brand_string
Apple M1
% ./cmk.darwin.arm64
zsh: killed     ./cmk.darwin.arm64
% ./cmk.darwin.x86-64
zsh: killed     ./cmk.darwin.x86-64

**Comment by rohityadavcloud** [comment] 2022-03-22 19:22
Yes @wongster80 pl use the darwin arm64 build from https://github.com/apache/cloudstack-cloudmonkey/releases/download/6.2.0/cmk.darwin.arm64

After downloading, don't forget to run `chmod +x <binary>`.

I tested this locally:
```
./cmk.darwin.arm64 -v
Apache CloudStack 🐵 CloudMonkey 6.2.0 (build: 2176ff6, 2021-10-27T17:14:21+0530)
```

**Comment by vseshan** [comment] 2022-03-24 00:22
Same here i have MacOS Monterey version 12.2.1 Macbook Pro Apple M1

**Comment by rohityadavcloud** [comment] 2022-03-24 09:02
@vseshan @wongster80 can you check and share the md5 checksum of the binary? See how I tested below:

```
bash-3.2$ wget https://github.com/apache/cloudstack-cloudmonkey/releases/download/6.2.0/cmk.darwin.arm64

...
Length: 7739714 (7.4M) [application/octet-stream]
Saving to: ‘cmk.darwin.arm64’

cmk.darwin.arm64                100%[======================================================>]   7.38M  6.64MB/s    in 1.1s

2022-03-24 14:31:14 (6.64 MB/s) - ‘cmk.darwin.arm64’ saved [7739714/7739714]

bash-3.2$ md5 cmk.darwin.arm64
MD5 (cmk.darwin.arm64) = 479f6c9132c216bfbf0e5e650021f625

bash-3.2$ chmod +x cmk.darwin.arm64
bash-3.2$ ./cmk.darwin.arm64 -v
Apache CloudStack 🐵 CloudMonkey 6.2.0 (build: 2176ff6, 2021-10-27T17:14:21+0530)
```

I'm not able to reproduce your error, though I've Macbook Air M1.

**Comment by vseshan** [comment] 2022-03-24 14:57
It works now, earlier we downloaded the binary directly from the browser now after downloading from wget it works.
Thanks for your help.
    On Thursday, March 24, 2022, 02:03:09 AM PDT, Rohit Yadav ***@***.***> wrote:  
 
 


@vseshan @wongster80 can you check and share the md5 checksum of the binary? See how I tested below:
bash-3.2$ wget https://github.com/apache/cloudstack-cloudmonkey/releases/download/6.2.0/cmk.darwin.arm64

...
Length: 7739714 (7.4M) [application/octet-stream]
Saving to: ‘cmk.darwin.arm64’

cmk.darwin.arm64                100%[======================================================>]   7.38M  6.64MB/s    in 1.1s

2022-03-24 14:31:14 (6.64 MB/s) - ‘cmk.darwin.arm64’ saved [7739714/7739714]

bash-3.2$ md5 cmk.darwin.arm64
MD5 (cmk.darwin.arm64) = 479f6c9132c216bfbf0e5e650021f625

bash-3.2$ chmod +x cmk.darwin.arm64
bash-3.2$ ./cmk.darwin.arm64 -v
Apache CloudStack 🐵 CloudMonkey 6.2.0 (build: 2176ff6, 2021-10-27T17:14:21+0530)

I'm not able to reproduce your error, though I've Macbook Air M1.

**Comment by rohityadavcloud** [comment] 2022-03-24 15:40
@vseshan I think it should still work, even if the link/cli is downloaded from browser (check the md5sum for example to confirm if the download via browser went well). It's possible Github was experiencing some issues which is resolved now.

@wongster80 is it the same issue for you, can you confirm if it works for you too?

**Comment by rohityadavcloud** [comment] 2022-05-11 05:52
Closing this, pl reopen with more information if this is still an issue for your @wongster80

**Closed by rohityadavcloud** 2022-05-11 05:52 UTC
