### ISSUE TITLE
Can't identify source problem on loading profile, ambigous error message

### ISSUE THREAD

**Issue by synergiator** [apache/cloudstack-cloudmonkey#73] opened 2021-02-08 09:37 UTC
# Summary

As it seems, error handling regarding loading of the API profile is not complete and/or according error message is ambiguous/wrong.

# Problem description

Consider the following test environment:

* Docker image with pytest in a Gitlab CI/CD runner
* Step 1: use direct Python call using `cs` (not required but as sanity check for the environment)
* Step 2: call cmk using `subprocess`
* Error: "_Please provide either apikey/secretkey or username/password to make an API call Error: failed to authenticate to make API call_" ([from here](https://github.com/apache/cloudstack-cloudmonkey/blob/2d9fd04d3276149331c774cbd1c731a48a9008a9/cmd/network.go#L217))

# Troubleshooting so far

What I've tried is:

* Login to runner VM and run the test script inside the corresponding Docker container hoping to reproduce the problem
* I can't reproduce the problem: as it is, the script is running through without error. If I try to modify test environment e.g. change credentials, then I get error from `cs`. If I change the way how `subprocess` is run, cmk can't be found
* After reading the linked source code, I can't understand the logic but it seems to me the problem captured in the `else` block, string length of credentials, does not relate to the error message it issues that there is an auth problem?

# Question
What is required to modify in the test environment so that the referenced `else` block is triggered?

**Comment by rhtyd** [comment] 2021-02-08 09:51
@synergiator can you check if you're using `cs` (https://github.com/exoscale/cs ?) or cmk (this repo). `cmk` is Go based and not Python based.

**Comment by synergiator** [comment] 2021-02-08 10:14
@rhtyd I use both consequently and independently in same environment:
* cs as Python dependency
* cmk as CLI tool called via Python `subprocess`

**Comment by synergiator** [comment] 2021-02-08 11:02
OK here is what has happened: it was not same file, and there is a catch and possible error source:
* the error above can be triggered if the config file is there but corrupted in some way
* in my case, using direct test session I had a default config file which was ok
* the CI/CD environment has a manually crafted paste-in config file which is created with `\r` line endings. These were read by `cs` but CloudMonkey assumes the variables for credentials are not present.



`cat` on config file in direct session:

b'[PROFILE_NAME]\n#comment..

`cat` in indirect session -> error

b'[PROFILE_NAME]\r url = https:....

**Comment by rhtyd** [comment] 2021-02-08 11:27
I'm not sure what exactly you're doing, the simplest fix is to do this manually and set a `cmk` profile with the correct username and password and then run it with cs or your custom script @synergiator , or do it in steps (such as set `cmk` profile name, url, apikey, secretkey or username/password) before calling anything else. Do you believe this is a `cmk` bug, or a `cs` or your script bug?

See for usage: https://github.com/apache/cloudstack-cloudmonkey/wiki/Usage

**Comment by synergiator** [comment] 2021-02-08 13:08
It's hard to say where the bug is but it's a mix of circumstances leading to the problem scenario which might be hard to pin down:

* For some reason, the user provides a config file which is syntactically correct but uses non-Linux line endings (in my setup, I used GitLab CI/CD's webform, leading to `\r` character as line ending)
* CloudMonkey does not parse these lines, does not recognize there is a problem with line endings, but does recognize it can't read the variables.
* I was not sure what the error "fail to auth, provide .." is about, if I provide variables as required. What has happened is actually a parse error (because of wrong line endings)
* The[ actual bug source](https://gitlab.com/gitlab-org/gitlab/-/issues/2940) is in this context how GitLab handles multi-line secret variables but I think the issue line endings is not specific to it

**Comment by rhtyd** [comment] 2021-04-28 10:24
Closing the issue as the issue is related to `cs` - https://github.com/exoscale/cs, and not CloudMonkey/`cmk` (the tool itself). The issue is with how cmk was called with an external script/tool.
@synergiator please raise issue around `cs` with https://github.com/exoscale/cs

**Closed by rhtyd** 2021-04-28 10:24 UTC
