### ISSUE TITLE
set profile doesn't change the client credentials 

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-cloudmonkey#42] opened 2019-01-18 08:18 UTC
```
(localcloud) SBCM5> > set profile localcloud
Loaded server profile: localcloud
Url:         http://10.2.2.113:8080/client/api
Username:    admin
Domain:      /
API Key:     LIN6rqXuaJwMPfGYFh13qDwYz5VNNz1J2J6qIOWcd3oLQOq0WtD4CwRundBL6rzXToa3lQOC_vKjI3nkHtiD8Q

(localcloud) SBCM5> > sync
Discovered 590 APIs
(localcloud) SBCM5> > set profile something
Loaded server profile: something
Url:         http://localhost:8080/client/api
Username:    admin
Domain:      /
API Key:

(something) SBCM5> > sync
Discovered 590 APIs
(something) SBCM5> >
```

As you can follow from the snippet above when changing the profile to some new one, one would expect an exception to be thrown when trying to sync. Instead it uses the old credentials for the root admin. Same goes if you try to set url api key ect... it simply does not take them into account but operates with the default ones.

**Comment by rhtyd** [comment] 2019-03-05 09:24
I couldn't reproduce this, I tested few scenarios. Closing this as I'm unable to reproduce, @borisstoyanov kindly test again once RC1 is out this week.

**Closed by rhtyd** 2019-03-05 09:24 UTC
