### ISSUE TITLE
If not sudo strange file lock error / CloudMonkey 6.0.0 (build: 74ff37c, 2019-03-05T17:27:26+0530)

### ISSUE THREAD

**Issue by synergiator** [apache/cloudstack-cloudmonkey#65] opened 2020-07-01 07:21 UTC
Just discovered this exception:
```

Failed to grab config file lock, please try again
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6973c1]

goroutine 1 [running]:
github.com/apache/cloudstack-cloudmonkey/config.(*Config).UpdateConfig(0xc0000a84e0, 0x76bbda, 0x6, 0x7ffec3d4f642, 0x5, 0x0)
	/home/rohit/lab/apache/cloudmonkey/config/config.go:283 +0x421
main.main()
	/home/rohit/lab/apache/cloudmonkey/cmk.go:63 +0x45e
```
Which files does `cmk` need to lock here?

Workaround: sudo

**Comment by rhtyd** [comment] 2020-07-01 07:26
@synergiator thanks for reporting the issue. Yes, cmk needs to create its config directory at $HOME/.cmk where it stores config, profiles etc. When running just make sure your user/process has access to allow cloudmonkey to create and manipulate its config/history/profile/cache files. This is not different from what cmk v6.0.0 does, can you test and check if you're getting the same issue with older (6.0.0) version of cloudmonkey as well? Or, it could be a permission fix (for example run: sudo chown -R <your-user>:<your-user> ~/.cmk in case the cmk config path/files are owned by root user)

Can you also share your platform and OS (such as x86_64, Linux) etc. Thanks.

**Comment by rhtyd** [comment] 2020-07-17 08:45
Any update @synergiator probably the ~/.cmk is not owned by your user?

**Comment by synergiator** [comment] 2020-07-17 08:53
hi there @rhtyd I think yes, this has been a constellation where the path was created by Docker as I used cmk inside a container mounted to local path. Can't reproduce anymore. The intention of this issue was just to maybe have a more explicit error message, telling the user in such occasion which files/folders could not be accessed exactly.

**Comment by rhtyd** [comment] 2020-07-27 06:38
Thanks closing as you can't reproduce this anymore.

**Closed by rhtyd** 2020-07-27 06:38 UTC
